{{- if .Values.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "performance-app.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  csi:
    driver: $driver_type
    volumeHandle: {{ .Values.pv.efs_id }}
    volumeAttributes:
      encryptInTransit: "true"
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.pv.accessModes }}
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  # hostPath:
  #   path: {{ .Values.pv.hostPath }}  # Replace with the actual path on your host machine
{{- end }}
---

{{- if .Values.createPV }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "performance-app.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.pv.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pv.capacity }}
  storageClassName: efs-sc
{{- end }}