---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kickstartdatabase-pvc
  namespace: kickstart-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-script
  namespace: kickstart-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
  volumeMode: Filesystem